events/urls.py
from django.urls import path

from . import views

app_name = 'events'

urlpatterns = [
    path('create/', views.EventCreate.as_view(), name='create'),
    path('<int:pk>/edit/', views.EventUpdate.as_view(), name='update'),
    path('<int:pk>/signup/', views.sign_up, name='sign-up'),
    path('<int:pk>/withdraw/', views.withdraw, name='withdraw'),
    path('<int:pk>/', views.EventDetail.as_view(), name='detail'),
    path('', views.EventList.as_view(), name='list'),
]

project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from rest_framework import routers
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView,
)

from events import api as events_api
from accounts import api as accounts_api

router = routers.DefaultRouter()
router.register(r'events', events_api.EventViewSet)
router.register(r'register', accounts_api.UserViewSet, basename='register')


urlpatterns = [
    path(
        'api/token/',
        TokenObtainPairView.as_view(),
        name='token-obtain-pair',
    ),
    path(
        'api/token/refresh/', TokenRefreshView.as_view(), name='token-refresh',
    ),
    path('api/token/verify/', TokenVerifyView.as_view(), name='token_verify'),
    path('api/', include(router.urls)),
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
    path('', include('events.urls', namespace='events')),
]

if settings.DEBUG:  # pragma: no cover
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT,
    )
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar  # noqa: WPS433
        urlpatterns = [
            path('__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns

templates/includes/footer.html
<footer class="py-5 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Your Website 2019 - {% now 'Y' %}</p>
    </div>
    <!-- /.container -->
</footer>

templates/includes/navigation.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="/">Events Web App</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'events:create' %}">Create event</a>
                </li>

                {% if user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownPortfolio" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{ request.user.email }}</a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownPortfolio">
                        <a class="dropdown-item" href="{% url 'profile' %}">Profile</a>
                        <a class="dropdown-item" href="{% url 'password_change' %}">Password change</a>
                        <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                    </div>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'signup' %}">Register</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}">Login</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

templates/includes/pagination.html
<div class="col-md-2 mx-auto">
    <ul class="pagination">
        {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
        {% endif %}
        {% if page_obj.has_next %}
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
        {% endif %}
    </ul>
</div>