events/urls.py
from django.urls import path

from . import views

app_name = 'events'

urlpatterns = [
    path('create/', views.EventCreate.as_view(), name='create'),
    path('<int:pk>/edit/', views.EventUpdate.as_view(), name='update'),
    path('<int:pk>/signup/', views.sign_up, name='sign-up'),
    path('<int:pk>/withdraw/', views.withdraw, name='withdraw'),
    path('<int:pk>/', views.EventDetail.as_view(), name='detail'),
    path('', views.EventList.as_view(), name='list'),
]

project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from rest_framework import routers
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView,
)

from events import api as events_api
from accounts import api as accounts_api

router = routers.DefaultRouter()
router.register(r'events', events_api.EventViewSet)
router.register(r'register', accounts_api.UserViewSet, basename='register')


urlpatterns = [
    path(
        'api/token/',
        TokenObtainPairView.as_view(),
        name='token-obtain-pair',
    ),
    path(
        'api/token/refresh/', TokenRefreshView.as_view(), name='token-refresh',
    ),
    path('api/token/verify/', TokenVerifyView.as_view(), name='token_verify'),
    path('api/', include(router.urls)),
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
    path('', include('events.urls', namespace='events')),
]

if settings.DEBUG:  # pragma: no cover
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT,
    )
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar  # noqa: WPS433
        urlpatterns = [
            path('__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns

events/models.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from .managers import EventManager


def get_sentinel_user():
    """Get or create deleted user.

    Returns:
        User: dummy user

    """
    return get_user_model().objects.get_or_create(
        username='deleted', email='deleted@foo.bar',
    )[0]


class Event(models.Model):
    """Event documentation."""

    title = models.CharField(_('title'), max_length=50)
    description = models.TextField(_('description'))
    date = models.DateField(_('date'))
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET(get_sentinel_user),
    )

    class Meta:
        verbose_name = _('event')
        verbose_name_plural = _('events')

    objects = EventManager()

    def __str__(self):
        """Whenever you call str() on an object.

        Returns:
            str: string representation

        """
        return self.title

    def get_absolute_url(self):
        """Event detail url."""  # noqa: DAR201
        return reverse('events:detail', args=[self.pk])

    def get_amount_of_participants(self):
        """Event participants count."""  # noqa: DAR201
        return self.eventparticipant_set.count()


class EventParticipant(models.Model):
    """Event participant."""

    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
    )

    class Meta:
        unique_together = [['event', 'user']]

events/forms.py
from django import forms

from .models import Event
from .validators import is_valid_event_date


class EventCreateForm(forms.ModelForm):
    """Event creation form."""

    class Meta:
        model = Event
        fields = ['title', 'description', 'date']

    def clean_date(self):
        """Check if future date.

        Returns:
            datetime: cleaned date
        """
        return is_valid_event_date(self.cleaned_data['date'])

events/views.py
# flake8: noqa: DAR201
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, redirect
from django.http.response import HttpResponseForbidden
from django.views.decorators.csrf import csrf_exempt
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.list import ListView

from .forms import EventCreateForm
from .models import Event


@login_required
def sign_up(request, pk):
    """Sign up for event."""
    event = get_object_or_404(Event.objects.incoming(), pk=pk)
    event.eventparticipant_set.get_or_create(event=event, user=request.user)
    return redirect(event.get_absolute_url())


@login_required
def withdraw(request, pk):
    """Withdraw from event."""
    event = get_object_or_404(Event, pk=pk)
    event.eventparticipant_set.filter(user=request.user).delete()
    return redirect(event.get_absolute_url())


class EventCreate(LoginRequiredMixin, CreateView):
    """Event create view."""

    model = Event
    template_name = 'events/event_form_create.html'
    form_class = EventCreateForm


    def form_valid(self, form):
        """Set Event owner."""  # noqa: DAR101, DAR201
        form.instance.user = self.request.user
        return super().form_valid(form)


class EventUpdate(LoginRequiredMixin, UpdateView):
    """Event update view."""

    model = Event
    fields = ['title', 'description', 'date']
    template_name = 'events/event_form_update.html'

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object.user != request.user:
            return HttpResponseForbidden()
        return super().post(request, *args, **kwargs)


class EventDetail(DetailView):
    """Event detail view."""

    model = Event

    def is_user_participate(self):
        """Check if logged user is a participant."""
        if self.request.user.is_anonymous:
            return False
        return self.object.eventparticipant_set.filter(
            user=self.request.user,
        ).exists()

    def get_context_data(self, **kwargs):
        """Add some extra data to context."""
        context = super().get_context_data(**kwargs)
        context.update({'is_user_participate': self.is_user_participate()})
        return context


class EventList(ListView):
    """Index view."""

    queryset = Event.objects.incoming()
    paginate_by = 12

templates/events/event_detail.html
{% extends "base.html" %}

{% block title %}{{ event.title|title }}{% endblock title %}

{% block content %}
<div class="container">

    <div class="row">

      <!-- Post Content Column -->
      <div class="col-lg-8">

        <!-- Title -->
        <h1 class="mt-4">{{ event.title|upper }}</h1>

        <!-- Author -->
        <p class="lead">
          event owner:
          <a href="#">{{ event.user.get_name }}</a>
        </p>

        <hr>

        <!-- Date/Time -->
        <p>event date: {{ event.date }}</p>

        <hr>

        <!-- Preview Image -->
        <img class="img-fluid rounded" src="http://placehold.it/900x300" alt="">

        <hr>

        <!-- Post Content -->
        <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus, vero, obcaecati, aut, error quam sapiente nemo saepe quibusdam sit excepturi nam quia corporis eligendi eos magni recusandae laborum minus inventore?</p>

        <p>{{ event.description }}</p>

      </div>

      <!-- Sidebar Widgets Column -->
      <div class="col-md-4">

        <!-- Search Widget -->
        {% if event.user == user %}
        <div class="card my-4">
          <h5 class="card-header">Actions</h5>
          <div class="card-body">
              <a href="{% url 'events:update' event.pk %}" class="btn btn-primary">Edit event</a>
          </div>
        </div>
        {% endif %}

        <!-- Categories Widget -->

        <!-- Side Widget -->
        <div class="card my-4">
          <h5 class="card-header">Participants</h5>
          <div class="card-body">
              Amount of participants: {{ event.num_participants }}
              <hr />
              {% if not is_user_participate %}
              <a href="{% url 'events:sign-up' event.pk %}" class="btn btn-success">Sign up</a>
              {% else %}
              <a href="{% url 'events:withdraw' event.pk %}" class="btn btn-danger">Withdraw</a>
              {% endif %}
          </div>
        </div>

      </div>

    </div>
    <!-- /.row -->

  </div>
    
{% endblock content %}

templates/events/event_form.html
{% extends "base.html" %}

{% block content %}
<div class="container py-5">
    <h1>{% block title %}{% endblock title %}</h1>
    <form action="" method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_title">{{ form.title.label }}</label>
            <input type="text" class="form-control" name="title" id="id_title" placeholder="Enter title here" value="{{ form.title.value|default:"" }}">
            <span class="text-danger">{{ form.title.errors }}</span>
        </div>
        <div class="form-group">
            <label for="id_date">{{ form.date.label }}</label>
            <input type="date" class="form-control" name="date" id="id_date" value="{{ event.date|date:"Y-m-d"}}">
            <span class="text-danger">{{ form.date.errors }}</span>
        </div>
        <div class="form-group">
            <label for="id_description">{{ form.description.label }}</label>
            <textarea class="form-control" name="description" id="id_description" rows="3" placeholder="Enter description here">{{ form.description.value|default:"" }}</textarea>
            <span class="text-danger">{{ form.description.errors }}</span>
        </div>
        <button type="submit" class="btn btn-primary">{% block submit %}Send{% endblock submit %}</button>
    </form>
</div>
{% endblock content %}

templates/events/event_form_create.html
{% extends "events/event_form.html" %}

{% block title %}Create new event{% endblock title %}

{% block submit %}Create{% endblock submit %}

templates/events/event_form_update.html
{% extends "events/event_form.html" %}

{% block title %}Edit event{% endblock title %}

{% block submit %}Edit{% endblock submit %}

templates/events/event_list.html
{% extends "base.html" %}

{% block content %}
    <div class="container">

        <!-- Jumbotron Header -->
        <header class="jumbotron my-4">
            <h1 class="display-3">A Warm Welcome!</h1>
            <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsa, ipsam, eligendi, in quo sunt possimus non incidunt odit vero aliquid similique quaerat nam nobis illo aspernatur vitae fugiat numquam repellat.</p>
            <a href="#" class="btn btn-primary btn-lg">Call to action!</a>
        </header>

        <!-- Page Features -->
        <div class="row text-center">
            {% if event_list %}
                {% for event in event_list %}
                    {% include "events/event_list_item.html" %}
                {% endfor %}
            {% else %}
                <p>There is no incomming events.</p>
            {% endif %}
        </div>

        {% include "includes/pagination.html" %}

        <!-- /.row -->

    </div>
{% endblock content %}

templates/events/event_list_item.html
<div class="col-lg-3 col-md-6 mb-4">
    <div class="card h-100">
        <!--
           -<img class="card-img-top" src="http://placehold.it/500x325" alt="">
           -->
        <div class="card-body">
            <h4 class="card-title">{{ event.title|upper }}</h4>
            <p class="cart-subtitle">owner: {{ event.user.get_name }}</p>
            <p class="cart-text">participants amount: {{ event.num_participants }}</p>
            <p class="card-text">date: {{ event.date }}</p>
        </div>
        <div class="card-footer">
            <a href="{{ event.get_absolute_url }}" class="btn btn-primary">Details</a>
        </div>
    </div>
</div>